export var intlPrefixes = `<option data-countrycode="PH" value="63" selected>PH (+63)</option>`;
/*
  <option disabled="disabled">Other Countries</option>
  <option data-countrycode="DZ" value="213">DZ (+213)</option>
  <option data-countrycode="AD" value="376">AD (+376)</option>
  <option data-countrycode="AO" value="244">AO (+244)</option>
  <option data-countrycode="AI" value="1264">AI (+1264)</option>
  <option data-countrycode="AG" value="1268">AG (+1268)</option>
  <option data-countrycode="AR" value="54">AR (+54)</option>
  <option data-countrycode="AM" value="374">AM (+374)</option>
  <option data-countrycode="AW" value="297">AW (+297)</option>
  <option data-countrycode="AU" value="61">AU (+61)</option>
  <option data-countrycode="AT" value="43">AT (+43)</option>
  <option data-countrycode="AZ" value="994">AZ (+994)</option>
  <option data-countrycode="BS" value="1242">BS (+1242)</option>
  <option data-countrycode="BH" value="973">BH (+973)</option>
  <option data-countrycode="BD" value="880">BD (+880)</option>
  <option data-countrycode="BB" value="1246">BB (+1246)</option>
  <option data-countrycode="BY" value="375">BY (+375)</option>
  <option data-countrycode="BE" value="32">BE (+32)</option>
  <option data-countrycode="BZ" value="501">BZ (+501)</option>
  <option data-countrycode="BJ" value="229">BJ (+229)</option>
  <option data-countrycode="BM" value="1441">BM (+1441)</option>
  <option data-countrycode="BT" value="975">BT (+975)</option>
  <option data-countrycode="BO" value="591">BO (+591)</option>
  <option data-countrycode="BA" value="387">BA (+387)</option>
  <option data-countrycode="BW" value="267">BW (+267)</option>
  <option data-countrycode="BR" value="55">BR (+55)</option>
  <option data-countrycode="BN" value="673">BN (+673)</option>
  <option data-countrycode="BG" value="359">BG (+359)</option>
  <option data-countrycode="BF" value="226">BF (+226)</option>
  <option data-countrycode="BI" value="257">BI (+257)</option>
  <option data-countrycode="KH" value="855">KH (+855)</option>
  <option data-countrycode="CM" value="237">CM (+237)</option>
  <option data-countrycode="CA" value="1">CA (+1)</option>
  <option data-countrycode="CV" value="238">CV (+238)</option>
  <option data-countrycode="KY" value="1345">KY (+1345)</option>
  <option data-countrycode="CF" value="236">CF (+236)</option>
  <option data-countrycode="CL" value="56">CL (+56)</option>
  <option data-countrycode="CN" value="86">CN (+86)</option>
  <option data-countrycode="CO" value="57">CO (+57)</option>
  <option data-countrycode="KM" value="269">KM (+269)</option>
  <option data-countrycode="CG" value="242">CG (+242)</option>
  <option data-countrycode="CK" value="682">CK (+682)</option>
  <option data-countrycode="CR" value="506">CR (+506)</option>
  <option data-countrycode="HR" value="385">HR (+385)</option>
  <!-- <option data-countryCode="CU" value="53">Cuba (+53)</option> -->
  <option data-countrycode="CY" value="90">CY (+90)</option>
  <option data-countrycode="CY" value="357">CY (+357)</option>
  <option data-countrycode="CZ" value="420">CZ (+420)</option>
  <option data-countrycode="DK" value="45">DK (+45)</option>
  <option data-countrycode="DJ" value="253">DJ (+253)</option>
  <option data-countrycode="DM" value="1809">DM (+1809)</option>
  <option data-countrycode="DO" value="1809">DO (+1809)</option>
  <option data-countrycode="EC" value="593">EC (+593)</option>
  <option data-countrycode="EG" value="20">EG (+20)</option>
  <option data-countrycode="SV" value="503">SV (+503)</option>
  <option data-countrycode="GQ" value="240">GQ (+240)</option>
  <option data-countrycode="ER" value="291">ER (+291)</option>
  <option data-countrycode="EE" value="372">EE (+372)</option>
  <option data-countrycode="ET" value="251">ET (+251)</option>
  <option data-countrycode="FK" value="500">FK (+500)</option>
  <option data-countrycode="FO" value="298">FO (+298)</option>
  <option data-countrycode="FJ" value="679">FJ (+679)</option>
  <option data-countrycode="FI" value="358">FI (+358)</option>
  <option data-countrycode="FR" value="33">FR (+33)</option>
  <option data-countrycode="GF" value="594">GF (+594)</option>
  <option data-countrycode="PF" value="689">PF (+689)</option>
  <option data-countrycode="GA" value="241">GA (+241)</option>
  <option data-countrycode="GM" value="220">GM (+220)</option>
  <option data-countrycode="GE" value="7880">GE (+7880)</option>
  <option data-countrycode="DE" value="49">DE (+49)</option>
  <option data-countrycode="GH" value="233">GH (+233)</option>
  <option data-countrycode="GI" value="350">GI (+350)</option>
  <option data-countrycode="GR" value="30">GR (+30)</option>
  <option data-countrycode="GL" value="299">GL (+299)</option>
  <option data-countrycode="GD" value="1473">GD (+1473)</option>
  <option data-countrycode="GP" value="590">GP (+590)</option>
  <option data-countrycode="GU" value="671">GU (+671)</option>
  <option data-countrycode="GT" value="502">GT (+502)</option>
  <option data-countrycode="GN" value="224">GN (+224)</option>
  <option data-countrycode="GW" value="245">GW (+245)</option>
  <option data-countrycode="GY" value="592">GY (+592)</option>
  <option data-countrycode="HT" value="509">HT (+509)</option>
  <option data-countrycode="HN" value="504">HN (+504)</option>
  <option data-countrycode="HK" value="852">HK (+852)</option>
  <option data-countrycode="HU" value="36">HU (+36)</option>
  <option data-countrycode="IS" value="354">IS (+354)</option>
  <option data-countrycode="IN" value="91">IN (+91)</option>
  <option data-countrycode="ID" value="62">ID (+62)</option>
  <option data-countrycode="IQ" value="964">IQ (+964)</option>
  <!-- <option data-countryCode="IR" value="98">Iran (+98)</option> -->
  <option data-countrycode="IE" value="353">IE (+353)</option>
  <option data-countrycode="IL" value="972">IL (+972)</option>
  <option data-countrycode="IT" value="39">IT (+39)</option>
  <option data-countrycode="JM" value="1876">JM (+1876)</option>
  <option data-countrycode="JP" value="81">JP (+81)</option>
  <option data-countrycode="JO" value="962">JO (+962)</option>
  <option data-countrycode="KZ" value="7">KZ (+7)</option>
  <option data-countrycode="KE" value="254">KE (+254)</option>
  <option data-countrycode="KI" value="686">KI (+686)</option>
  <!-- <option data-countryCode="KP" value="850">Korea - North (+850)</option> -->
  <option data-countrycode="KR" value="82">KR (+82)</option>
  <option data-countrycode="KW" value="965">KW (+965)</option>
  <option data-countrycode="KG" value="996">KG (+996)</option>
  <option data-countrycode="LA" value="856">LA (+856)</option>
  <option data-countrycode="LV" value="371">LV (+371)</option>
  <option data-countrycode="LB" value="961">LB (+961)</option>
  <option data-countrycode="LS" value="266">LS (+266)</option>
  <option data-countrycode="LR" value="231">LR (+231)</option>
  <option data-countrycode="LY" value="218">LY (+218)</option>
  <option data-countrycode="LI" value="417">LI (+417)</option>
  <option data-countrycode="LT" value="370">LT (+370)</option>
  <option data-countrycode="LU" value="352">LU (+352)</option>
  <option data-countrycode="MO" value="853">MO (+853)</option>
  <option data-countrycode="MK" value="389">MK (+389)</option>
  <option data-countrycode="MG" value="261">MG (+261)</option>
  <option data-countrycode="MW" value="265">MW (+265)</option>
  <option data-countrycode="MY" value="60">MY (+60)</option>
  <option data-countrycode="MV" value="960">MV (+960)</option>
  <option data-countrycode="ML" value="223">ML (+223)</option>
  <option data-countrycode="MT" value="356">MT (+356)</option>
  <option data-countrycode="MH" value="692">MH (+692)</option>
  <option data-countrycode="MQ" value="596">MQ (+596)</option>
  <option data-countrycode="MR" value="222">MR (+222)</option>
  <option data-countrycode="YT" value="269">YT (+269)</option>
  <option data-countrycode="MX" value="52">MX (+52)</option>
  <option data-countrycode="FM" value="691">FM (+691)</option>
  <option data-countrycode="MD" value="373">MD (+373)</option>
  <option data-countrycode="MC" value="377">MC (+377)</option>
  <option data-countrycode="MN" value="976">MN (+976)</option>
  <option data-countrycode="MS" value="1664">MS (+1664)</option>
  <option data-countrycode="MA" value="212">MA (+212)</option>
  <option data-countrycode="MZ" value="258">MZ (+258)</option>
  <option data-countrycode="MN" value="95">MN (+95)</option>
  <option data-countrycode="NA" value="264">NA (+264)</option>
  <option data-countrycode="NR" value="674">NR (+674)</option>
  <option data-countrycode="NP" value="977">NP (+977)</option>
  <option data-countrycode="NL" value="31">NL (+31)</option>
  <option data-countrycode="NC" value="687">NC (+687)</option>
  <option data-countrycode="NZ" value="64">NZ (+64)</option>
  <option data-countrycode="NI" value="505">NI (+505)</option>
  <option data-countrycode="NE" value="227">NE (+227)</option>
  <option data-countrycode="NG" value="234">NG (+234)</option>
  <option data-countrycode="NU" value="683">NU (+683)</option>
  <option data-countrycode="NF" value="672">NF (+672)</option>
  <option data-countrycode="NP" value="670">NP (+670)</option>
  <option data-countrycode="NO" value="47">NO (+47)</option>
  <option data-countrycode="OM" value="968">OM (+968)</option>
  <option data-countrycode="PK" value="92">PK (+92)</option>
  <option data-countrycode="PW" value="680">PW (+680)</option>
  <option data-countrycode="PA" value="507">PA (+507)</option>
  <option data-countrycode="PG" value="675">PG (+675)</option>
  <option data-countrycode="PY" value="595">PY (+595)</option>
  <option data-countrycode="PE" value="51">PE (+51)</option>
  <option data-countrycode="PL" value="48">PL (+48)</option>
  <option data-countrycode="PT" value="351">PT (+351)</option>
  <option data-countrycode="PR" value="1787">PR (+1787)</option>
  <option data-countrycode="QA" value="974">QA (+974)</option>
  <option data-countrycode="RE" value="262">RE (+262)</option>
  <option data-countrycode="RO" value="40">RO (+40)</option>
  <option data-countrycode="RU" value="7">RU (+7)</option>
  <option data-countrycode="RW" value="250">RW (+250)</option>
  <option data-countrycode="SM" value="378">SM (+378)</option>
  <option data-countrycode="ST" value="239">ST (+239)</option>
  <option data-countrycode="SA" value="966">SA (+966)</option>
  <option data-countrycode="SN" value="221">SN (+221)</option>
  <option data-countrycode="CS" value="381">CS (+381)</option>
  <option data-countrycode="SC" value="248">SC (+248)</option>
  <option data-countrycode="SL" value="232">SL (+232)</option>
  <option data-countrycode="SG" value="65">SG (+65)</option>
  <option data-countrycode="SK" value="421">SK (+421)</option>
  <option data-countrycode="SI" value="386">SI (+386)</option>
  <option data-countrycode="SB" value="677">SB (+677)</option>
  <option data-countrycode="SO" value="252">SO (+252)</option>
  <option data-countrycode="ZA" value="27">ZA (+27)</option>
  <option data-countrycode="ES" value="34">ES (+34)</option>
  <option data-countrycode="LK" value="94">LK (+94)</option>
  <option data-countrycode="SH" value="290">SH (+290)</option>
  <option data-countrycode="KN" value="1869">KN (+1869)</option>
  <option data-countrycode="SC" value="1758">SC (+1758)</option>
  <option data-countrycode="SR" value="597">SR (+597)</option>
  <option data-countrycode="SD" value="249">SD (+249)</option>
  <option data-countrycode="SZ" value="268">SZ (+268)</option>
  <option data-countrycode="SE" value="46">SE (+46)</option>
  <option data-countrycode="CH" value="41">CH (+41)</option>
  <!-- <option data-countryCode="SY" value="963">Syria (+963)</option> -->
  <option data-countrycode="TW" value="886">TW (+886)</option>
  <option data-countrycode="TJ" value="992">TJ (+992)</option>
  <option data-countrycode="TH" value="66">TH (+66)</option>
  <option data-countrycode="TG" value="228">TG (+228)</option>
  <option data-countrycode="TO" value="676">TO (+676)</option>
  <option data-countrycode="TT" value="1868">TT (+1868)</option>
  <option data-countrycode="TN" value="216">TN (+216)</option>
  <option data-countrycode="TR" value="90">TR (+90)</option>
  <option data-countrycode="TM" value="993">TM (+993)</option>
  <option data-countrycode="TC" value="1649">TC (+1649)</option>
  <option data-countrycode="TV" value="688">TV (+688)</option>
  <option data-countrycode="UG" value="256">UG (+256)</option>
  <option data-countrycode="GB" value="44">GB (+44)</option>
  <option data-countrycode="UA" value="380">UA (+380)</option>
  <option data-countrycode="AE" value="971">AE (+971)</option>
  <option data-countrycode="US" value="1">US (+1)</option>
  <option data-countrycode="UY" value="598">UY (+598)</option>
  <option data-countrycode="UZ" value="998">UZ (+998)</option>
  <option data-countrycode="VU" value="678">VU (+678)</option>
  <option data-countrycode="VA" value="379">VA (+379)</option>
  <option data-countrycode="VE" value="58">VE (+58)</option>
  <option data-countrycode="VN" value="84">VN (+84)</option>
  <option data-countrycode="VG" value="1">VG (+1)</option>
  <option data-countrycode="VI" value="1">VI (+1)</option>
  <option data-countrycode="WF" value="681">WF (+681)</option>
  <option data-countrycode="YE" value="969">YE (+969)</option>
  <option data-countrycode="YE" value="967">YE (+967)</option>
  <option data-countrycode="ZM" value="260">ZM (+260)</option>
  <option data-countrycode="ZW" value="263">ZW (+263)</option>`; */